# Here’s a complete Python code to run transformers in Google Colab using Hugging Face's transformers library and a relevant dataset for text classification:

In [3]:
# Install necessary libraries
!pip install transformers
!pip install datasets
!pip install torch

# Import libraries
from transformers import pipeline
from datasets import load_dataset

# Load a pre-trained transformer model for text classification (e.g., BERT)
classifier = pipeline("text-classification", model="bert-base-uncased")

# Load a sample dataset for sentiment analysis
dataset = load_dataset("imdb", split='test[:1%]')

# Example text from the dataset
texts = dataset["text"]

# Predict the sentiment for the first few texts
for text in texts[:5]:
    result = classifier(text)
    print(f"Text: {text[:100]}...")  # print a preview of the text
    print(f"Prediction: {result}\n")


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.6 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

unsupervised-00000-of-00001.parquet:   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Text: I love sci-fi and am willing to put up with a lot. Sci-fi movies/TV are usually underfunded, under-a...
Prediction: [{'label': 'LABEL_1', 'score': 0.5970489978790283}]

Text: Worth the entertainment value of a rental, especially if you like action movies. This one features t...
Prediction: [{'label': 'LABEL_1', 'score': 0.5395856499671936}]

Text: its a totally average film with a few semi-alright action sequences that make the plot seem a little...
Prediction: [{'label': 'LABEL_1', 'score': 0.5738851428031921}]

Text: STAR RATING: ***** Saturday Night **** Friday Night *** Friday Morning ** Sunday Night * Monday Morn...
Prediction: [{'label': 'LABEL_1', 'score': 0.5091767907142639}]

Text: First off let me say, If you haven't enjoyed a Van Damme movie since bloodsport, you probably will n...
Prediction: [{'label': 'LABEL_1', 'score': 0.5659682154655457}]



## Using transformers with Custom Model Architecture

In [5]:
# Install necessary libraries
!pip install transformers
!pip install torch

# Import necessary libraries
import torch
import torch.nn as nn
from transformers import BertModel, BertTokenizer

class CustomTransformerModel(nn.Module):
    def __init__(self):
        super(CustomTransformerModel, self).__init__()
        # Load pre-trained BERT model
        self.bert = BertModel.from_pretrained("bert-base-uncased")
        self.fc = nn.Linear(self.bert.config.hidden_size, 2)  # For binary classification

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        logits = self.fc(pooled_output)
        return logits

# Initialize model and tokenizer
model = CustomTransformerModel()
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Example input
text = "This is a great example of how to use transformers."
inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

# Forward pass through the model
logits = model(inputs["input_ids"], attention_mask=inputs["attention_mask"])
print(logits)


tensor([[-0.6817, -0.0505]], grad_fn=<AddmmBackward0>)


In [6]:
print(logits)

tensor([[-0.6817, -0.0505]], grad_fn=<AddmmBackward0>)


## Using transformers with Pre-trained Models for Text Generation

In [7]:
# Install necessary libraries
!pip install transformers
!pip install torch

# Import libraries
from transformers import GPT2LMHeadModel, GPT2Tokenizer

# Load pre-trained GPT-2 model and tokenizer
model_name = "gpt2"
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

# Encode input text (prompt)
input_text = "Once upon a time, in a land far away"
inputs = tokenizer.encode(input_text, return_tensors="pt")

# Generate output text
output = model.generate(inputs, max_length=50, num_return_sequences=1, no_repeat_ngram_size=2)

# Decode the generated tokens into text
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)

print(generated_text)


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Once upon a time, in a land far away, the world was a place of peace and harmony. The world of the gods was the land of gods, and the earth was their home.

The gods were the people of this land,


## Using transformers for Named Entity Recognition (NER)

In [12]:
# Install necessary libraries
!pip install transformers
!pip install torch

# Import libraries
from transformers import pipeline

# Load pre-trained NER model
ner_model = pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english")

# Example text
text = "Elon Musk is the CEO of SpaceX and Tesla."

# Run NER
entities = ner_model(text)

for entity in entities:
    print(f"Entity: {entity['word']}, Label: {entity['entity']}, Confidence: {entity['score']}")


Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Entity: El, Label: I-PER, Confidence: 0.9995798468589783
Entity: ##on, Label: I-PER, Confidence: 0.9990248680114746
Entity: Mu, Label: I-PER, Confidence: 0.9993333220481873
Entity: ##sk, Label: I-PER, Confidence: 0.9984556436538696
Entity: Space, Label: I-ORG, Confidence: 0.999152421951294
Entity: ##X, Label: I-ORG, Confidence: 0.9986114501953125
Entity: Te, Label: I-ORG, Confidence: 0.9964274764060974
Entity: ##sla, Label: I-ORG, Confidence: 0.9953011274337769


## Using transformers with TensorFlow

In [13]:
# Install necessary libraries
!pip install transformers
!pip install tensorflow

# Import libraries
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer
import tensorflow as tf

# Load pre-trained model and tokenizer for TensorFlow
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# Example input text
text = "Transformers are powerful models in NLP."

# Tokenize the input text
inputs = tokenizer(text, return_tensors="tf", truncation=True, padding=True, max_length=512)

# Predict with TensorFlow model
logits = model(**inputs).logits
print(logits)


All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tf.Tensor([[ 0.14732714 -0.01170861]], shape=(1, 2), dtype=float32)
